# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'BaseProject' do
  use_frameworks!

  pod 'SwiftLint'

  target 'BaseProjectTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'BaseProjectUITests' do
    inherit! :search_paths
  end

end
